### ISSUE TITLE
reflect-metadata 0.1.9 triggers "read only property" TypeError

### ISSUE THREAD

**Issue by tvsbrent** [inversify/inversify-basic-example#7]
Compiling with 0.1.9 of `reflect-metadata` causes the following exception:

```
D:\Repos\inversify-basic-example\node_modules\inversify\lib\resolution\instantiation.js:14
        instance[propertyName] = injection;
                               ^
TypeError: Cannot assign to read only property 'warrior1' of object '#<EpicBattle>'
```
Downgrading to 0.1.8 corrects the issue.

**Comment by remojansen** [comment]
Hi @tvsbrent thanks for reporting this. I will work on a fix ASAP but due to xmas it may take me a few of days.

**Comment by tvsbrent** [comment]
No problem, I didn't expect such a quick response!

**Comment by remojansen** [comment]
Done by ae38fdcb7499ce57513cc659d6c808fad0ba3c9f
